# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    group:
        label: adrenth.coffeemanager::lang.participants.filter.group
        modelClass: Adrenth\CoffeeManager\Models\Group
        conditions: group_id in (:filtered)
        nameFrom: name

    default_beverage:
        label: adrenth.coffeemanager::lang.participants.filter.default_beverage
        modelClass: Adrenth\CoffeeManager\Models\Beverage
        conditions: default_beverage_id in (:filtered)
        nameFrom: name

    last_beverage:
        label: adrenth.coffeemanager::lang.participants.filter.last_beverage
        modelClass: Adrenth\CoffeeManager\Models\Beverage
        conditions: last_beverage_id in (:filtered)
        nameFrom: name
