# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    group:
        label: adrenth.coffeemanager::lang.beverages.filter.group
        modelClass: Adrenth\CoffeeManager\Models\BeverageGroup
        conditions: group_id in (:filtered)
        nameFrom: name
